### PR TITLE
outdated version 

### PR DESCRIPTION
**Pull request by BaronClaps**

### CODE REVIEW

**Comment by BeepBot99** [comment]
This repo isn't even being used rn 💀

**Comment by BaronClaps** [comment]
> This repo isn't even being used rn 💀
🤫

**Comment by BeepBot99** [comment]
Please read [CONTRUBITING.md](https://github.com/rowan-mcalpin/NextFTC/blob/main/CONTRIBUTING.md) before making a pull request.

**Comment by rowan-mcalpin** [comment]
Already implemented

**Comment by BeepBot99** [comment]
Yeah baron it's already implemented

**Comment by BaronClaps** [comment]
Bruh.

**Pull request closed without merging**
